travis:
  secure:
    BINSTAR_TOKEN: tI3y5hcqQOqvyHriBNrwvwxtiOoBJypMQWL5DoHawg7T4tFY5+hzriXs0H0tauqbxOnfF9g55HDPv+azQG1KjF9lpN7gKEqlhXJFsoE+mV+FOF93iSwMef3DnkbqP0tKtlBqNEhv7VClJGmLE22pUOaLzIsKWARlhffQq8E1fao2s+QjC8GgFHO1y31iaZaDwC6G0fO7MmjlcnNj7SgtBTmzHKd59lVRadxkVzqrIPt/RVVJ5FIvdOjwTezX4Lv3tPtKAEqN41Igzud8DdRvB1JKqogqj8b39YC4rN/ifVzxAkVJjh4cArYdg10arkXcmG87od68DqnVWr2K9ZdzmjI/Jqf5SbJoBkNEr881V1oz/FN1eTdTbcAYDc7ac78zGJkms7hulwAuvX5avXRw1L956ZACI6voEIyl9HHRK6loQXq2b+0wt2fxXLuOYd84v2n0kl3rhjbfttdinKP/Z4WFvbjp3RvfSdYVcKz3cRUMWZD9pJaoccGwoYugBUzXogG8dEjH+SPp/DGcC/SWELF+KCR+n5wZP62NQknJxZrNNPeyRKBjkfCbnbhxEN31SIGE4Nfw+2zyWsjkRCcPWzZBTq4eM0tYKraJE81d3Bsyq/vBGCaAyC7UxIBZ9iLYIcB9X9JQEEc1Z57c7Bd99sPLMZm3EjVhx4k4hKabPDA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
